name: Build and Auto Release .deb Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Create .deb package
        run: |
          mkdir -p tigerfetch_pkg/DEBIAN
          mkdir -p tigerfetch_pkg/usr/bin

          cp tigerfetch tigerfetch_pkg/usr/bin/tigerfetch
          chmod 755 tigerfetch_pkg/usr/bin/tigerfetch

          VERSION=$(date +%Y.%m.%d.%H%M)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

          cat <<EOF > tigerfetch_pkg/DEBIAN/control
          Package: tigerfetch
          Version: $VERSION
          Section: base
          Priority: optional
          Architecture: all
          Depends: python3, python3-psutil, figlet, pciutils
          Maintainer: Charles Santana
          Description: Tigerfetch - Uma ferramenta simples para exibir informações do sistema estilo Neofetch.
          EOF

          dpkg-deb --build tigerfetch_pkg
          mv tigerfetch_pkg.deb tigerfetch-${{ env.PACKAGE_VERSION }}.deb

      - name: Create GitHub Release and Upload .deb
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.PACKAGE_VERSION }}
          name: Tigerfetch v${{ env.PACKAGE_VERSION }}
          artifacts: tigerfetch-${{ env.PACKAGE_VERSION }}.deb
          token: ${{ secrets.GITHUB_TOKEN }}
